### PR TITLE
remove duplicate linum configuration

### PR DESCRIPTION
**Pull request by deb0ch**

### CODE REVIEW

**Comment by oneKelvinSmith** [comment]
Hey @deb0ch, I'm sorry I didn't see this earlier. Would you mind updating your PR to the last master version? I managed to get some time/motivation to update the theme.

**Comment by deb0ch** [comment]
No problemo, working on it :+1:

**Comment by deb0ch** [comment]
Tadaaaaaa :tada: :sparkles: :confetti_ball: :metal:

**Comment by oneKelvinSmith** [comment]
Cheers :)

**Pull request merged**
